//<![CDATA[
var dataOrder = {
	"Dandi Trihatmojo": {
        "screenshotURL": "",
        "avaURL": "https://cf.shopee.co.id/file/4e701787442a4ebbe6b777ea4d53a5a7_tn",
		"lokasi": "Samarinda",
        "time": "2020-08-11",
        "template": "License Wisecare 365 Pro",
        "templateURL": "https://www.almaftuchin.com/produk/license-wise-care-365-pro-lifetime",
    },
	"Dedy Ardiansyah": {
        "screenshotURL": "",
        "avaURL": "https://cf.shopee.co.id/file/cc4d736c42393a2eb0d463ac09203c41_tn",
		"lokasi": "Sabang",
        "time": "2020-08-11",
        "template": "Hetman Partition Recovery Home Edition",
        "templateURL": "https://www.almaftuchin.com/produk/license-hetman-partition-recovery-pro-lifetime",
    },
    "Dedy Ardiansyah": {
        "screenshotURL": "",
        "avaURL": "https://cf.shopee.co.id/file/cc4d736c42393a2eb0d463ac09203c41_tn",
		"lokasi": "Sabang",
        "time": "2020-08-11",
        "template": "License Nitro Pro 13",
        "templateURL": "https://www.almaftuchin.com/produk/license-nitro-pro-13-lifetime",
    },
    "Dedy Ardiansyah": {
        "screenshotURL": "",
        "avaURL": "https://cf.shopee.co.id/file/cc4d736c42393a2eb0d463ac09203c41_tn",
		"lokasi": "Sabang",
        "time": "2020-08-12",
        "template": "WinRAR Pro Lifetime",
        "templateURL": "https://www.almaftuchin.com/produk/license-winrar-pro-lifetime/",
    },
    "Rudini": {
        "screenshotURL": "",
        "avaURL": "",
		"lokasi": "Tangerang Selatan",
        "time": "2020-08-13",
        "template": "License Techsmith Snagit 2020 Lifetime",
        "templateURL": "https://www.almaftuchin.com/produk/license-techsmith-snagit-pro-lifetime",
    },
    "Mashut": {
        "screenshotURL": "",
        "avaURL": "https://cf.shopee.co.id/file/8bc7b04f50c85e21439e39fe31a81c2a_tn",
		"lokasi": "Semarang",
        "time": "2020-08-13",
        "template": "License Malwarebytes Anti-Malware Corporate",
        "templateURL": "https://www.almaftuchin.com/produk/license-malwarebytes-anti-malware-corporate-lifetime",
    },
    "Amry Yunarto": {
        "screenshotURL": "",
        "avaURL": "https://cf.shopee.co.id/file/af6815a04f085c5f93bf3d448af4246c_tn",
		"lokasi": "Karawang",
        "time": "2020-08-15",
        "template": "License VMWare Workstation 16 Pro For 10 PC",
        "templateURL": "https://www.almaftuchin.com/produk/license-vmware-workstation-16-pro-lifetime",
    },
    "Wardiansah": {
        "screenshotURL": "",
        "avaURL": "",
		"lokasi": "Palembang",
        "time": "2020-08-16",
        "template": "License AIDA64 Bundle Packs",
        "templateURL": "https://www.almaftuchin.com/produk/license-aida64-bundle-packs-lifetime",
    },
    "Wardiansah": {
        "screenshotURL": "",
        "avaURL": "",
		"lokasi": "Palembang",
        "time": "2020-08-16",
        "template": "License WinRAR Pro 2020",
        "templateURL": "https://www.almaftuchin.com/produk/license-winrar-pro-lifetime",
    },
    "Wardiansah": {
        "screenshotURL": "",
        "avaURL": "",
		"lokasi": "Palembang",
        "time": "2020-08-16",
        "template": "License Nitro Pro 12",
        "templateURL": "https://www.almaftuchin.com/produk/license-nitro-pro-12-lifetime",
    },
    "Naamma Firdausiya": {
        "screenshotURL": "",
        "avaURL": "https://cf.shopee.co.id/file/6fe38fce64f73fd6bff9493645d79e50_tn",
		"lokasi": "Sleman",
        "time": "2020-08-16",
        "template": "License HD Tune 5.75 Pro 3 PC",
        "templateURL": "https://www.almaftuchin.com/produk/license-hd-tune-pro-lifetime",
    },
    "Kasito": {
        "screenshotURL": "",
        "avaURL": "https://cf.shopee.co.id/file/fa4a02522395f34767c897c3c59457b7_tn",
		"lokasi": "Tangerang",
        "time": "2020-08-17",
        "template": "License Nitro Pro 12",
        "templateURL": "https://www.almaftuchin.com/produk/license-nitro-pro-12-lifetime",
    },
    "Azmi": {
        "screenshotURL": "",
        "avaURL": "",
		"lokasi": "Batam",
        "time": "2020-08-17",
        "template": "License ZD Screen Recorder 2020",
        "templateURL": "https://www.almaftuchin.com/produk/license-zd-screen-recorder-pro-lifetime",
    },
    "Nur Aina": {
        "screenshotURL": "",
        "avaURL": "",
		"lokasi": "Ponorogo",
        "time": "2020-08-05",
        "template": "License Faststone Capture Pro",
        "templateURL": "https://www.almaftuchin.com/produk/license-faststone-capture-pro-lifetime",
    },
    "Erry": {
        "screenshotURL": "",
        "avaURL": "https://cf.shopee.co.id/file/9b0b82ad1dd70acc08852672bd438e45_tn",
		"lokasi": "Bengkalis",
        "time": "2020-08-04",
        "template": "License Top Password Protect My Folders",
        "templateURL": "https://www.almaftuchin.com/produk/license-top-password-protect-my-folders-pro-lifetime",
    },
    "Yenni Masni Astuti": {
        "screenshotURL": "",
        "avaURL": "",
		"lokasi": "Sintang",
        "time": "2020-08-04",
        "template": "License Faststone Capture Pro",
        "templateURL": "https://www.almaftuchin.com/produk/license-faststone-capture-pro-lifetime",
    },
    "Indra Utama Soeherwin": {
        "screenshotURL": "",
        "avaURL": "",
		"lokasi": "Jakarta Selatan",
        "time": "2020-08-03",
        "template": "License AOMEI Partition Assistant Professional",
        "templateURL": "https://www.almaftuchin.com/produk/license-aomei-partition-assistant-professional-lifetime",
    },
    "Moh Fadel Ammar": {
        "screenshotURL": "",
        "avaURL": "https://cf.shopee.co.id/file/03336431332c2e04e82c0774ad997f6c_tn",
		"lokasi": "Makassar",
        "time": "2020-08-02",
        "template": "License Jilbit Macro Recorder Pro",
        "templateURL": "https://www.almaftuchin.com/produk/license-jilbit-macro-recorder-pro-lifetime",
    },
    "Teti Kurniawati": {
        "screenshotURL": "",
        "avaURL": "https://cf.shopee.co.id/file/0f52f7d42f95e17eaca8dd55d9330115_tn",
		"lokasi": "Bekasi",
        "time": "2020-08-11",
        "template": "License Minitool Power Data Recovery 7",
        "templateURL": "https://www.almaftuchin.com/produk/license-mini-tool-power-data-recovery-7-personal-edition-lifetime",
    },
    "Edwin Jaya": {
        "screenshotURL": "",
        "avaURL": "https://cf.shopee.co.id/file/d041fff9ed9831b79cb1d2250bd5fefe_tn",
		"lokasi": "Jakarta Utara",
        "time": "2020-08-02",
        "template": "License PowerISO Pro",
        "templateURL": "https://www.almaftuchin.com/produk/license-power-iso-pro-lifetime",
    },
    "Rohmadi": {
        "screenshotURL": "",
        "avaURL": "https://cf.shopee.co.id/file/0f52f7d42f95e17eaca8dd55d9330115_tn",
		"lokasi": "Palembang",
        "time": "2020-08-11",
        "template": "License Nitro Pro 13",
        "templateURL": "https://www.almaftuchin.com/produk/license-nitro-pro-13-lifetime",
    },
};
//]]>
